version: '2'
services:
    redis:
        image: redis:5
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - webnet
    postgres:
        image: postgres:11
        volumes:
            - data-volume:/data/db
        # command: -p 5434
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
            # POSTGRES_HOST: ${DATABASE_HOST}
        networks:
            - webnet
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            # - xpack.security.transport.ssl.verification_mode=none
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            # - xpack.security.transport.ssl.verification_mode=none
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data02:/usr/share/elasticsearch/data
        networks:
            - elastic
    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            # - xpack.security.transport.ssl.verification_mode=none
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data03:/usr/share/elasticsearch/data
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
        container_name: kib01
        # volumes:
            # - certs:/usr/share/kibana/config/certs
            # - kibanadata:/usr/share/kibana/data
        ports:
            - ${KIBANA_PORT}:5601
        environment:
            # - SERVERNAME=kibana
            - ELASTICSEARCH_URL=http://es01:9200
            - ELASTICSEARCH_HOSTS=http://es01:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
            # - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
        # mem_limit: ${MEM_LIMIT}
        networks:
            - elastic
networks:
    elastic:
        driver: bridge
    webnet:
volumes:
    data-volume:
    data01:
        driver: local
    data02:
        driver: local
    data03:
        driver: local
    # kibanadata:
    #     driver: local
